FROM jupyterhub/jupyterhub:latest

# feature_jupyterhub
ARG hnnuiBranch=feature_jupyterhub 
ENV hnnuiBranch=${hnnuiBranch}  
RUN echo "$hnnuiBranch";

# Install authenticator and spawner + jupyter_client
RUN pip install jupyterhub-tmpauthenticator dockerspawner jupyter_client

# Overwrite jupyterhub_config
RUN wget https://raw.githubusercontent.com/MetaCell/HNN-UI/$hnnuiBranch/jupyterhub/jupyterhub_config.py -q