FROM metacell/jupyter-neuron:latest

USER root
RUN conda install -c conda-forge nodejs configurable-http-proxy

USER $NB_USER

# feature_jupyterhub
ARG hnnuiBranch=feature_jupyterhub  
ENV hnnuiBranch=${hnnuiBranch}  
RUN echo "$hnnuiBranch";

ARG INCUBATOR_VER=unknown
RUN /bin/bash -c "INCUBATOR_VER=${INCUBATOR_VER} source activate snakes && pip install jupyterhub==0.9.4"

# Clone HNN-UI and install the development version
RUN wget https://github.com/MetaCell/HNN-UI/archive/$hnnuiBranch.zip -q
RUN unzip $hnnuiBranch.zip
WORKDIR /home/jovyan/work/HNN-UI-$hnnuiBranch/utilities
RUN /bin/bash -c "source activate snakes && python --version"
RUN /bin/bash -c "source activate snakes && exec python install.py branch $hnnuiBranch"

# Compile mods
WORKDIR /home/jovyan/HNN-UI-$hnnuiBranch/hnn_ui/mod
RUN nrnivmodl
RUN cp -r x86_64 ../../

# Copy jupyterhub_config
# RUN cp /home/jovyan/work/HNN-UI-$hnnuiBranch/jupyterhub_config.py .
WORKDIR /home/jovyan/HNN-UI-$hnnuiBranch
CMD /bin/bash -c "source activate snakes && exec jupyterhub-singleuser --debug --NotebookApp.default_url=/geppetto --NotebookApp.token='' --library=hnn_ui"
